// <auto-generated />
using System;
using HospitalLibrary.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalLibrary.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20221109183158_BloodMigration")]
    partial class BloodMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FloorRoom", b =>
                {
                    b.Property<int>("FloorsId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomsId")
                        .HasColumnType("integer");

                    b.HasKey("FloorsId", "RoomsId");

                    b.HasIndex("RoomsId");

                    b.ToTable("FloorRoom");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Bed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Beds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            Available = true,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 3,
                            Available = false,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 4,
                            Available = true,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 5,
                            Available = false,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 6,
                            Available = false,
                            RoomId = 3
                        });
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Blood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Bloods");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.BloodUnitRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountL")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BloodUnitRequests");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndWork")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartWork")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndWork = new DateTime(2022, 11, 16, 1, 56, 46, 40, DateTimeKind.Utc).AddTicks(9800),
                            FirstName = "firstName",
                            LastName = "lastName",
                            RoomId = 1,
                            StartWork = new DateTime(2022, 11, 16, 1, 56, 46, 40, DateTimeKind.Utc).AddTicks(9798)
                        },
                        new
                        {
                            Id = 2,
                            EndWork = new DateTime(2022, 11, 16, 1, 56, 46, 40, DateTimeKind.Utc).AddTicks(9805),
                            FirstName = "firstNam2",
                            LastName = "lastName2",
                            RoomId = 1,
                            StartWork = new DateTime(2022, 11, 16, 1, 56, 46, 40, DateTimeKind.Utc).AddTicks(9804)
                        });
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Examination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RoomId");

                    b.ToTable("Examinations");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateOnly(2022, 10, 24),
                            IsAnonymous = true,
                            IsPublic = true,
                            PatientId = 1,
                            Status = 0,
                            Text = "Bolnica je dobra"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateOnly(2022, 10, 24),
                            IsAnonymous = false,
                            IsPublic = true,
                            PatientId = 2,
                            Status = 0,
                            Text = "Bolnica je losa"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateOnly(2022, 10, 24),
                            IsAnonymous = false,
                            IsPublic = true,
                            PatientId = 3,
                            Status = 1,
                            Text = "Bolnica je odlicna"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateOnly(2022, 10, 24),
                            IsAnonymous = true,
                            IsPublic = true,
                            PatientId = 4,
                            Status = 0,
                            Text = "Bolnica je solidna"
                        });
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.ITherapySubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ITherapySubject");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ITherapySubject");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Pera",
                            LastName = "Peric"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Marko",
                            LastName = "Markovic"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Dusan",
                            LastName = "Baljinac"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Slobodan",
                            LastName = "Radulovic"
                        });
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Therapy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("PrescribedId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TreatmentHistoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WhenPrescribed")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PrescribedId");

                    b.HasIndex("TreatmentHistoryId");

                    b.ToTable("Therapies");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.TreatmentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("BedId")
                        .HasColumnType("integer");

                    b.Property<string>("DischargeReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BedId");

                    b.HasIndex("PatientId");

                    b.ToTable("TreatmentHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            BedId = 1,
                            DischargeReason = "abc",
                            EndDate = new DateTime(2022, 11, 16, 1, 56, 46, 40, DateTimeKind.Utc).AddTicks(9918),
                            PatientId = 1,
                            StartDate = new DateTime(2022, 11, 16, 1, 56, 46, 40, DateTimeKind.Utc).AddTicks(9917)
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            BedId = 2,
                            DischargeReason = "abc",
                            EndDate = new DateTime(2022, 11, 16, 1, 56, 46, 40, DateTimeKind.Utc).AddTicks(9928),
                            PatientId = 2,
                            StartDate = new DateTime(2022, 11, 16, 1, 56, 46, 40, DateTimeKind.Utc).AddTicks(9927)
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            BedId = 3,
                            DischargeReason = "abc",
                            EndDate = new DateTime(2022, 11, 16, 1, 56, 46, 40, DateTimeKind.Utc).AddTicks(9932),
                            PatientId = 3,
                            StartDate = new DateTime(2022, 11, 16, 1, 56, 46, 40, DateTimeKind.Utc).AddTicks(9931)
                        });
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "gray",
                            Height = 150,
                            Name = "One",
                            Width = 450,
                            X = 100,
                            Y = 100
                        },
                        new
                        {
                            Id = 2,
                            Color = "gray",
                            Height = 450,
                            Name = "Too",
                            Width = 150,
                            X = 600,
                            Y = 100
                        },
                        new
                        {
                            Id = 3,
                            Color = "gray",
                            Height = 130,
                            Name = "Tre",
                            Width = 400,
                            X = 400,
                            Y = 600
                        });
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            BuildingId = 1,
                            Color = "white",
                            Height = 100,
                            Number = "Floor 3",
                            Width = 300,
                            X = 100,
                            Y = 70
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 1,
                            Color = "white",
                            Height = 100,
                            Number = "Floor 2",
                            Width = 300,
                            X = 100,
                            Y = 170
                        },
                        new
                        {
                            Id = 1,
                            BuildingId = 1,
                            Color = "white",
                            Height = 100,
                            Number = "Floor 1",
                            Width = 300,
                            X = 100,
                            Y = 270
                        },
                        new
                        {
                            Id = 5,
                            BuildingId = 2,
                            Color = "white",
                            Height = 100,
                            Number = "Floor 2",
                            Width = 300,
                            X = 100,
                            Y = 170
                        },
                        new
                        {
                            Id = 4,
                            BuildingId = 2,
                            Color = "white",
                            Height = 100,
                            Number = "Floor 1",
                            Width = 300,
                            X = 100,
                            Y = 270
                        },
                        new
                        {
                            Id = 8,
                            BuildingId = 3,
                            Color = "white",
                            Height = 100,
                            Number = "Floor 3",
                            Width = 300,
                            X = 100,
                            Y = 70
                        },
                        new
                        {
                            Id = 7,
                            BuildingId = 3,
                            Color = "white",
                            Height = 100,
                            Number = "Floor 2",
                            Width = 300,
                            X = 100,
                            Y = 170
                        },
                        new
                        {
                            Id = 6,
                            BuildingId = 3,
                            Color = "white",
                            Height = 100,
                            Number = "Floor 1",
                            Width = 300,
                            X = 100,
                            Y = 270
                        });
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.Map.MapBuilding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId")
                        .IsUnique();

                    b.ToTable("MapBuildings");
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.Map.MapFloor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FloorId")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FloorId")
                        .IsUnique();

                    b.ToTable("MapFloors");
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.Map.MapRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MapRooms");
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FloorId")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            FloorId = 1,
                            Height = 160,
                            Name = "Pedijatrija",
                            Type = 0,
                            Width = 260,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 2,
                            Color = "blue",
                            FloorId = 1,
                            Height = 140,
                            Name = "Kafeterija",
                            Type = 0,
                            Width = 220,
                            X = 0,
                            Y = 338
                        },
                        new
                        {
                            Id = 3,
                            Color = "blue",
                            FloorId = 1,
                            Height = 180,
                            Name = "Otorinolaringologija",
                            Type = 0,
                            Width = 300,
                            X = 237,
                            Y = 0
                        },
                        new
                        {
                            Id = 4,
                            Color = "blue",
                            FloorId = 2,
                            Height = 100,
                            Name = "Fizioterapeut",
                            Type = 0,
                            Width = 200,
                            X = 270,
                            Y = 378
                        },
                        new
                        {
                            Id = 5,
                            Color = "blue",
                            FloorId = 2,
                            Height = 180,
                            Name = "Stomatologija",
                            Type = 0,
                            Width = 360,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 6,
                            Color = "blue",
                            FloorId = 3,
                            Height = 180,
                            Name = "Magacin",
                            Type = 0,
                            Width = 260,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 7,
                            Color = "blue",
                            FloorId = 3,
                            Height = 140,
                            Name = "Opsta nega",
                            Type = 0,
                            Width = 220,
                            X = 0,
                            Y = 338
                        },
                        new
                        {
                            Id = 8,
                            Color = "blue",
                            FloorId = 3,
                            Height = 140,
                            Name = "Cekaonica",
                            Type = 0,
                            Width = 220,
                            X = 330,
                            Y = 158
                        },
                        new
                        {
                            Id = 9,
                            Color = "blue",
                            FloorId = 4,
                            Height = 170,
                            Name = "Kardiologija",
                            Type = 0,
                            Width = 320,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 10,
                            Color = "blue",
                            FloorId = 4,
                            Height = 140,
                            Name = "Vaskularne bolesti",
                            Type = 0,
                            Width = 220,
                            X = 0,
                            Y = 365
                        },
                        new
                        {
                            Id = 11,
                            Color = "blue",
                            FloorId = 4,
                            Height = 140,
                            Name = "Hirurgija",
                            Type = 0,
                            Width = 220,
                            X = 245,
                            Y = 0
                        },
                        new
                        {
                            Id = 12,
                            Color = "blue",
                            FloorId = 5,
                            Height = 140,
                            Name = "Papirologija",
                            Type = 0,
                            Width = 220,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 13,
                            Color = "blue",
                            FloorId = 5,
                            Height = 140,
                            Name = "Prijavna soba",
                            Type = 0,
                            Width = 220,
                            X = 200,
                            Y = 0
                        },
                        new
                        {
                            Id = 14,
                            Color = "blue",
                            FloorId = 5,
                            Height = 140,
                            Name = "Uplasta/isplata",
                            Type = 0,
                            Width = 220,
                            X = 0,
                            Y = 350
                        },
                        new
                        {
                            Id = 15,
                            Color = "blue",
                            FloorId = 5,
                            Height = 140,
                            Name = "Izgubljeno/nadjeno",
                            Type = 0,
                            Width = 220,
                            X = 200,
                            Y = 350
                        },
                        new
                        {
                            Id = 16,
                            Color = "blue",
                            FloorId = 6,
                            Height = 190,
                            Name = "Onkologija",
                            Type = 0,
                            Width = 320,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 17,
                            Color = "blue",
                            FloorId = 6,
                            Height = 240,
                            Name = "Onkologija",
                            Type = 0,
                            Width = 250,
                            X = 200,
                            Y = 300
                        },
                        new
                        {
                            Id = 18,
                            Color = "blue",
                            FloorId = 7,
                            Height = 280,
                            Name = "Gastronomija",
                            Type = 0,
                            Width = 420,
                            X = 50,
                            Y = 100
                        },
                        new
                        {
                            Id = 19,
                            Color = "blue",
                            FloorId = 8,
                            Height = 170,
                            Name = "Magacin",
                            Type = 0,
                            Width = 320,
                            X = 100,
                            Y = 138
                        });
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.BloodUnit", b =>
                {
                    b.HasBaseType("HospitalLibrary.Core.Model.ITherapySubject");

                    b.Property<int>("AmountMl")
                        .HasColumnType("integer");

                    b.Property<int>("BloodType")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("BloodUnit");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.MedicalDrugs", b =>
                {
                    b.HasBaseType("HospitalLibrary.Core.Model.ITherapySubject");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("MedicalDrugs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Drugs1",
                            Type = 0
                        });
                });

            modelBuilder.Entity("FloorRoom", b =>
                {
                    b.HasOne("HospitalLibrary.GraphicalEditor.Model.Floor", null)
                        .WithMany()
                        .HasForeignKey("FloorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalLibrary.GraphicalEditor.Model.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Bed", b =>
                {
                    b.HasOne("HospitalLibrary.GraphicalEditor.Model.Room", "Room")
                        .WithMany("Beds")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Doctor", b =>
                {
                    b.HasOne("HospitalLibrary.GraphicalEditor.Model.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Examination", b =>
                {
                    b.HasOne("HospitalLibrary.Core.Model.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalLibrary.Core.Model.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalLibrary.GraphicalEditor.Model.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Feedback", b =>
                {
                    b.HasOne("HospitalLibrary.Core.Model.Patient", "Patient")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Therapy", b =>
                {
                    b.HasOne("HospitalLibrary.Core.Model.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalLibrary.Core.Model.ITherapySubject", "Prescribed")
                        .WithMany()
                        .HasForeignKey("PrescribedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalLibrary.Core.Model.TreatmentHistory", null)
                        .WithMany("Therapies")
                        .HasForeignKey("TreatmentHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Prescribed");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.TreatmentHistory", b =>
                {
                    b.HasOne("HospitalLibrary.Core.Model.Bed", "Bed")
                        .WithMany()
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalLibrary.Core.Model.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.Floor", b =>
                {
                    b.HasOne("HospitalLibrary.GraphicalEditor.Model.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.Map.MapBuilding", b =>
                {
                    b.HasOne("HospitalLibrary.GraphicalEditor.Model.Building", "Building")
                        .WithOne("Map")
                        .HasForeignKey("HospitalLibrary.GraphicalEditor.Model.Map.MapBuilding", "BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.Map.MapFloor", b =>
                {
                    b.HasOne("HospitalLibrary.GraphicalEditor.Model.Floor", "Floor")
                        .WithOne("Map")
                        .HasForeignKey("HospitalLibrary.GraphicalEditor.Model.Map.MapFloor", "FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Patient", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.TreatmentHistory", b =>
                {
                    b.Navigation("Therapies");
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.Building", b =>
                {
                    b.Navigation("Floors");

                    b.Navigation("Map")
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.Floor", b =>
                {
                    b.Navigation("Map")
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.Room", b =>
                {
                    b.Navigation("Beds");
                });
#pragma warning restore 612, 618
        }
    }
}
